-- ============================================================================
-- 0002_seed_flavor_taxonomy.sql
-- Palato — Phase 0 schema seed
-- Date: May 2, 2026
-- ----------------------------------------------------------------------------
-- Imports the 168-row Palato flavor taxonomy (v01) into flavor_descriptors.
-- Source: palato-flavor-taxonomy-v01.csv
-- Wrapped in a transaction: all 168 rows land or none do.
-- ============================================================================

begin;

insert into public.flavor_descriptors
  (category, subcategory, descriptor, slug, aliases, is_defect, description,
   category_icon_color, category_pill_tint, sort_order)
values
  ('Fruit', 'Berry', 'Blueberry', 'blueberry', ARRAY['blueberries', 'blueberry jam']::text[], FALSE, 'Deep, sweet-tart berry. Classic natural Ethiopia note.', '#C84028', '#F5C7BC', 10),
  ('Fruit', 'Berry', 'Blackberry', 'blackberry', ARRAY['blackberries']::text[], FALSE, 'Dark, jammy berry with depth.', '#C84028', '#F5C7BC', 20),
  ('Fruit', 'Berry', 'Raspberry', 'raspberry', ARRAY['raspberries']::text[], FALSE, 'Bright, tart red berry. Often in high-grown washed coffees.', '#C84028', '#F5C7BC', 30),
  ('Fruit', 'Berry', 'Strawberry', 'strawberry', ARRAY['strawberries']::text[], FALSE, 'Sweet, pink berry. Common in naturals.', '#C84028', '#F5C7BC', 40),
  ('Fruit', 'Berry', 'Cranberry', 'cranberry', ARRAY['cranberries']::text[], FALSE, 'Sharp, tart red berry.', '#C84028', '#F5C7BC', 50),
  ('Fruit', 'Berry', 'Black currant', 'black-currant', ARRAY['cassis', 'black currants']::text[], FALSE, 'Intense, dark, musky berry. Cassis.', '#C84028', '#F5C7BC', 60),
  ('Fruit', 'Berry', 'Red currant', 'red-currant', ARRAY['red currants']::text[], FALSE, 'Tart, translucent red berry.', '#C84028', '#F5C7BC', 70),
  ('Fruit', 'Berry', 'Gooseberry', 'gooseberry', ARRAY['gooseberries']::text[], FALSE, 'Green, tart, slightly tropical berry.', '#C84028', '#F5C7BC', 80),
  ('Fruit', 'Berry', 'Mulberry', 'mulberry', ARRAY['mulberries']::text[], FALSE, 'Dark, winey berry.', '#C84028', '#F5C7BC', 90),
  ('Fruit', 'Stone fruit', 'Peach', 'peach', ARRAY['peaches', 'white peach']::text[], FALSE, 'Soft, sweet, juicy stone fruit.', '#C84028', '#F5C7BC', 100),
  ('Fruit', 'Stone fruit', 'Apricot', 'apricot', ARRAY['apricots']::text[], FALSE, 'Orange-fleshed, slightly tart stone fruit.', '#C84028', '#F5C7BC', 110),
  ('Fruit', 'Stone fruit', 'Nectarine', 'nectarine', ARRAY['nectarines']::text[], FALSE, 'Peach''s smooth cousin. Brighter, firmer.', '#C84028', '#F5C7BC', 120),
  ('Fruit', 'Stone fruit', 'Red plum', 'red-plum', ARRAY['plum', 'plums']::text[], FALSE, 'Sweet-tart purple-red fruit.', '#C84028', '#F5C7BC', 130),
  ('Fruit', 'Stone fruit', 'Black plum', 'black-plum', ARRAY['prune plum']::text[], FALSE, 'Deeper, winey plum.', '#C84028', '#F5C7BC', 140),
  ('Fruit', 'Stone fruit', 'Red cherry', 'red-cherry', ARRAY['cherry', 'cherries']::text[], FALSE, 'Classic sweet red stone fruit.', '#C84028', '#F5C7BC', 150),
  ('Fruit', 'Stone fruit', 'Dark cherry', 'dark-cherry', ARRAY['black cherry', 'bing cherry']::text[], FALSE, 'Deep, winey, dark-fleshed cherry.', '#C84028', '#F5C7BC', 160),
  ('Fruit', 'Tropical fruit', 'Mango', 'mango', NULL, FALSE, 'Ripe, lush, golden tropical fruit.', '#C84028', '#F5C7BC', 170),
  ('Fruit', 'Tropical fruit', 'Pineapple', 'pineapple', NULL, FALSE, 'Sweet-tart yellow tropical fruit.', '#C84028', '#F5C7BC', 180),
  ('Fruit', 'Tropical fruit', 'Papaya', 'papaya', NULL, FALSE, 'Soft, musky, orange tropical fruit.', '#C84028', '#F5C7BC', 190),
  ('Fruit', 'Tropical fruit', 'Passion fruit', 'passion-fruit', ARRAY['passionfruit']::text[], FALSE, 'Intensely aromatic, tart, seedy tropical.', '#C84028', '#F5C7BC', 200),
  ('Fruit', 'Tropical fruit', 'Guava', 'guava', NULL, FALSE, 'Pink-fleshed, musky-sweet tropical.', '#C84028', '#F5C7BC', 210),
  ('Fruit', 'Tropical fruit', 'Lychee', 'lychee', ARRAY['litchi']::text[], FALSE, 'Floral, grape-like tropical fruit.', '#C84028', '#F5C7BC', 220),
  ('Fruit', 'Tropical fruit', 'Banana', 'banana', NULL, FALSE, 'Sweet, creamy, sometimes starchy.', '#C84028', '#F5C7BC', 230),
  ('Fruit', 'Tropical fruit', 'Coconut', 'coconut', NULL, FALSE, 'Creamy, nutty-tropical. Sometimes crosses into nutty.', '#C84028', '#F5C7BC', 240),
  ('Fruit', 'Citrus fruit', 'Lemon', 'lemon', NULL, FALSE, 'Bright, sharp yellow citrus.', '#C84028', '#F5C7BC', 250),
  ('Fruit', 'Citrus fruit', 'Lime', 'lime', NULL, FALSE, 'Sharp, green citrus. Sometimes leaf-like.', '#C84028', '#F5C7BC', 260),
  ('Fruit', 'Citrus fruit', 'Orange', 'orange', NULL, FALSE, 'Sweet, balanced classic citrus.', '#C84028', '#F5C7BC', 270),
  ('Fruit', 'Citrus fruit', 'Grapefruit', 'grapefruit', NULL, FALSE, 'Bitter-sweet, pink or white citrus.', '#C84028', '#F5C7BC', 280),
  ('Fruit', 'Citrus fruit', 'Tangerine', 'tangerine', ARRAY['mandarin']::text[], FALSE, 'Soft, sweet, honeyed orange citrus.', '#C84028', '#F5C7BC', 290),
  ('Fruit', 'Citrus fruit', 'Bergamot', 'bergamot', NULL, FALSE, 'Perfumed citrus. Earl Grey character.', '#C84028', '#F5C7BC', 300),
  ('Fruit', 'Citrus fruit', 'Yuzu', 'yuzu', NULL, FALSE, 'Japanese citrus — lime-meets-mandarin with pine.', '#C84028', '#F5C7BC', 310),
  ('Fruit', 'Citrus fruit', 'Blood orange', 'blood-orange', NULL, FALSE, 'Berry-tinged, deeper orange.', '#C84028', '#F5C7BC', 320),
  ('Fruit', 'Citrus fruit', 'Meyer lemon', 'meyer-lemon', NULL, FALSE, 'Softer, sweeter lemon with floral edges.', '#C84028', '#F5C7BC', 330),
  ('Fruit', 'Pome fruit', 'Red apple', 'red-apple', ARRAY['apple']::text[], FALSE, 'Sweet, juicy classic apple.', '#C84028', '#F5C7BC', 340),
  ('Fruit', 'Pome fruit', 'Green apple', 'green-apple', ARRAY['granny smith']::text[], FALSE, 'Tart, crisp, unripe-style apple.', '#C84028', '#F5C7BC', 350),
  ('Fruit', 'Pome fruit', 'Pear', 'pear', NULL, FALSE, 'Soft, honeyed, delicate tree fruit.', '#C84028', '#F5C7BC', 360),
  ('Fruit', 'Pome fruit', 'Asian pear', 'asian-pear', NULL, FALSE, 'Crisp, watery, floral pear.', '#C84028', '#F5C7BC', 370),
  ('Fruit', 'Pome fruit', 'Quince', 'quince', NULL, FALSE, 'Aromatic, firm, honey-floral relative of apple.', '#C84028', '#F5C7BC', 380),
  ('Fruit', 'Dried fruit', 'Raisin', 'raisin', ARRAY['raisins', 'sultana']::text[], FALSE, 'Concentrated dried grape. Often in darker roasts.', '#C84028', '#F5C7BC', 390),
  ('Fruit', 'Dried fruit', 'Date', 'date', ARRAY['dates', 'medjool']::text[], FALSE, 'Deeply sweet, caramelly dried fruit.', '#C84028', '#F5C7BC', 400),
  ('Fruit', 'Dried fruit', 'Fig', 'fig', ARRAY['figs', 'dried fig']::text[], FALSE, 'Jammy, seedy, sweet dried fruit.', '#C84028', '#F5C7BC', 410),
  ('Fruit', 'Dried fruit', 'Prune', 'prune', ARRAY['prunes']::text[], FALSE, 'Dark, rich dried plum.', '#C84028', '#F5C7BC', 420),
  ('Fruit', 'Dried fruit', 'Dried apricot', 'dried-apricot', NULL, FALSE, 'Chewy, concentrated apricot.', '#C84028', '#F5C7BC', 430),
  ('Fruit', 'Dried fruit', 'Currant', 'currant', ARRAY['dried currants', 'zante']::text[], FALSE, 'Small, concentrated dried grape.', '#C84028', '#F5C7BC', 440),
  ('Floral', 'Floral', 'Jasmine', 'jasmine', NULL, FALSE, 'Classic high-toned floral. Washed Ethiopias.', '#A8456F', '#F2D4DE', 10),
  ('Floral', 'Floral', 'Rose', 'rose', ARRAY['rose water', 'rose hip']::text[], FALSE, 'Perfumed, romantic floral. Common in Geshas.', '#A8456F', '#F2D4DE', 20),
  ('Floral', 'Floral', 'Orange blossom', 'orange-blossom', ARRAY['neroli']::text[], FALSE, 'Bright citrus-floral.', '#A8456F', '#F2D4DE', 30),
  ('Floral', 'Floral', 'Honeysuckle', 'honeysuckle', NULL, FALSE, 'Sweet, dewy summer floral.', '#A8456F', '#F2D4DE', 40),
  ('Floral', 'Floral', 'Lavender', 'lavender', NULL, FALSE, 'Purple, slightly herbal floral.', '#A8456F', '#F2D4DE', 50),
  ('Floral', 'Floral', 'Hibiscus', 'hibiscus', NULL, FALSE, 'Tart, red, tea-like floral.', '#A8456F', '#F2D4DE', 60),
  ('Floral', 'Floral', 'Chamomile', 'chamomile', NULL, FALSE, 'Soft, apple-adjacent herbal floral.', '#A8456F', '#F2D4DE', 70),
  ('Floral', 'Floral', 'Elderflower', 'elderflower', NULL, FALSE, 'Light, bright, slightly musky floral.', '#A8456F', '#F2D4DE', 80),
  ('Floral', 'Floral', 'Violet', 'violet', NULL, FALSE, 'Dusky, candied purple floral.', '#A8456F', '#F2D4DE', 90),
  ('Floral', 'Floral', 'Lilac', 'lilac', NULL, FALSE, 'Cool, sweet spring floral.', '#A8456F', '#F2D4DE', 100),
  ('Floral', 'Tea-like', 'Black tea', 'black-tea', ARRAY['breakfast tea']::text[], FALSE, 'Tannic, malty. Think Assam or Ceylon.', '#A8456F', '#F2D4DE', 110),
  ('Floral', 'Tea-like', 'Green tea', 'green-tea', ARRAY['sencha']::text[], FALSE, 'Grassy, vegetal, bright tea character.', '#A8456F', '#F2D4DE', 120),
  ('Floral', 'Tea-like', 'Earl Grey', 'earl-grey', ARRAY['earl grey']::text[], FALSE, 'Bergamot-laced black tea.', '#A8456F', '#F2D4DE', 130),
  ('Floral', 'Tea-like', 'White tea', 'white-tea', NULL, FALSE, 'Delicate, pale, slightly floral tea.', '#A8456F', '#F2D4DE', 140),
  ('Sweet', 'Sugar & syrup', 'Raw sugar', 'raw-sugar', ARRAY['turbinado', 'demerara']::text[], FALSE, 'Amber crystal sugar with mild molasses.', '#A67A28', '#F2D9A5', 10),
  ('Sweet', 'Sugar & syrup', 'White sugar', 'white-sugar', ARRAY['refined sugar']::text[], FALSE, 'Clean, neutral sweetness.', '#A67A28', '#F2D9A5', 20),
  ('Sweet', 'Sugar & syrup', 'Molasses', 'molasses', NULL, FALSE, 'Dark, bitter-edged, mineral sweet.', '#A67A28', '#F2D9A5', 30),
  ('Sweet', 'Sugar & syrup', 'Maple syrup', 'maple-syrup', ARRAY['maple']::text[], FALSE, 'Woodsy, buttery, plant-sweet.', '#A67A28', '#F2D9A5', 40),
  ('Sweet', 'Sugar & syrup', 'Cane sugar', 'cane-sugar', ARRAY['sugarcane']::text[], FALSE, 'Clean, grassy-tinged sweet.', '#A67A28', '#F2D9A5', 50),
  ('Sweet', 'Vanilla & caramel', 'Vanilla', 'vanilla', ARRAY['vanilla bean']::text[], FALSE, 'Soft, aromatic, creamy sweet.', '#A67A28', '#F2D9A5', 60),
  ('Sweet', 'Vanilla & caramel', 'Caramel', 'caramel', NULL, FALSE, 'Cooked sugar with butter depth.', '#A67A28', '#F2D9A5', 70),
  ('Sweet', 'Vanilla & caramel', 'Butterscotch', 'butterscotch', NULL, FALSE, 'Butter-and-brown-sugar cooked together.', '#A67A28', '#F2D9A5', 80),
  ('Sweet', 'Vanilla & caramel', 'Toffee', 'toffee', NULL, FALSE, 'Darker, firmer caramel with nutty edges.', '#A67A28', '#F2D9A5', 90),
  ('Sweet', 'Brown sugar', 'Brown sugar', 'brown-sugar', NULL, FALSE, 'Molassed, soft, warm sweetness.', '#A67A28', '#F2D9A5', 100),
  ('Sweet', 'Brown sugar', 'Panela', 'panela', ARRAY['rapadura', 'jaggery']::text[], FALSE, 'Unrefined raw cane sugar. Earthy-sweet.', '#A67A28', '#F2D9A5', 110),
  ('Sweet', 'Honey', 'Honey', 'honey', NULL, FALSE, 'Floral, liquid sweetness. Clover, wildflower, etc.', '#A67A28', '#F2D9A5', 120),
  ('Sweet', 'Honey', 'Honeycomb', 'honeycomb', NULL, FALSE, 'Honey plus waxy, slightly bitter edges.', '#A67A28', '#F2D9A5', 130),
  ('Sweet', 'Confectionery', 'Marshmallow', 'marshmallow', NULL, FALSE, 'Soft, airy vanilla-sweet.', '#A67A28', '#F2D9A5', 140),
  ('Nutty & Cocoa', 'Nuts', 'Almond', 'almond', ARRAY['almonds', 'marzipan']::text[], FALSE, 'Dry, slightly sweet, classic nutty.', '#7A4C32', '#D9B99C', 10),
  ('Nutty & Cocoa', 'Nuts', 'Hazelnut', 'hazelnut', ARRAY['hazelnuts', 'filbert']::text[], FALSE, 'Rich, buttery, roasted nutty.', '#7A4C32', '#D9B99C', 20),
  ('Nutty & Cocoa', 'Nuts', 'Walnut', 'walnut', ARRAY['walnuts']::text[], FALSE, 'Oily, slightly bitter, earthy nut.', '#7A4C32', '#D9B99C', 30),
  ('Nutty & Cocoa', 'Nuts', 'Pecan', 'pecan', ARRAY['pecans']::text[], FALSE, 'Buttery, sweet, richer than walnut.', '#7A4C32', '#D9B99C', 40),
  ('Nutty & Cocoa', 'Nuts', 'Peanut', 'peanut', ARRAY['peanuts', 'peanut butter']::text[], FALSE, 'Roasty, oily, sometimes raw-green.', '#7A4C32', '#D9B99C', 50),
  ('Nutty & Cocoa', 'Nuts', 'Cashew', 'cashew', ARRAY['cashews']::text[], FALSE, 'Soft, creamy, mildly sweet nut.', '#7A4C32', '#D9B99C', 60),
  ('Nutty & Cocoa', 'Nuts', 'Pistachio', 'pistachio', ARRAY['pistachios']::text[], FALSE, 'Green, faintly resinous nut.', '#7A4C32', '#D9B99C', 70),
  ('Nutty & Cocoa', 'Nuts', 'Macadamia', 'macadamia', NULL, FALSE, 'Buttery, rich, smooth nut.', '#7A4C32', '#D9B99C', 80),
  ('Nutty & Cocoa', 'Cocoa', 'Milk chocolate', 'milk-chocolate', NULL, FALSE, 'Sweet, creamy chocolate.', '#7A4C32', '#D9B99C', 90),
  ('Nutty & Cocoa', 'Cocoa', 'Dark chocolate', 'dark-chocolate', NULL, FALSE, 'Bittersweet, rich chocolate.', '#7A4C32', '#D9B99C', 100),
  ('Nutty & Cocoa', 'Cocoa', 'Cocoa nib', 'cocoa-nib', ARRAY['cacao nib', 'cacao']::text[], FALSE, 'Raw, bitter, floral-edged cocoa.', '#7A4C32', '#D9B99C', 110),
  ('Nutty & Cocoa', 'Cocoa', 'Cocoa powder', 'cocoa-powder', ARRAY['unsweetened cocoa']::text[], FALSE, 'Dry, dusty, bitter cocoa.', '#7A4C32', '#D9B99C', 120),
  ('Nutty & Cocoa', 'Cocoa', 'Baker''s chocolate', 'bakers-chocolate', ARRAY['bakers chocolate', 'unsweetened chocolate']::text[], FALSE, 'Intense, unsweetened cocoa mass.', '#7A4C32', '#D9B99C', 130),
  ('Spice', 'Warming spices', 'Cinnamon', 'cinnamon', NULL, FALSE, 'Sweet-warm bark spice.', '#A8481F', '#F0BFA5', 10),
  ('Spice', 'Warming spices', 'Nutmeg', 'nutmeg', NULL, FALSE, 'Woodsy, warm, slightly sweet spice.', '#A8481F', '#F0BFA5', 20),
  ('Spice', 'Warming spices', 'Clove', 'clove', ARRAY['cloves']::text[], FALSE, 'Sharp, pungent, medicinal-sweet spice.', '#A8481F', '#F0BFA5', 30),
  ('Spice', 'Warming spices', 'Cardamom', 'cardamom', NULL, FALSE, 'Bright, citrus-edged, cool-warm spice.', '#A8481F', '#F0BFA5', 40),
  ('Spice', 'Warming spices', 'Allspice', 'allspice', NULL, FALSE, 'Clove-cinnamon-nutmeg blended spice note.', '#A8481F', '#F0BFA5', 50),
  ('Spice', 'Warming spices', 'Anise', 'anise', ARRAY['star anise']::text[], FALSE, 'Licorice-like, sweet spice.', '#A8481F', '#F0BFA5', 60),
  ('Spice', 'Pepper & savory', 'Black pepper', 'black-pepper', NULL, FALSE, 'Sharp, warming, pungent heat.', '#A8481F', '#F0BFA5', 70),
  ('Spice', 'Pepper & savory', 'White pepper', 'white-pepper', NULL, FALSE, 'Earthier, muskier pepper.', '#A8481F', '#F0BFA5', 80),
  ('Spice', 'Pepper & savory', 'Pink peppercorn', 'pink-peppercorn', NULL, FALSE, 'Floral, fruity, light pepper.', '#A8481F', '#F0BFA5', 90),
  ('Spice', 'Pepper & savory', 'Ginger', 'ginger', NULL, FALSE, 'Fresh, citrusy, pungent root spice.', '#A8481F', '#F0BFA5', 100),
  ('Spice', 'Pepper & savory', 'Juniper', 'juniper', ARRAY['juniper berry']::text[], FALSE, 'Pine-forward, resinous berry spice.', '#A8481F', '#F0BFA5', 110),
  ('Spice', 'Pepper & savory', 'Fennel', 'fennel', ARRAY['fennel seed']::text[], FALSE, 'Anise-cousin, grassy-sweet spice.', '#A8481F', '#F0BFA5', 120),
  ('Spice', 'Pepper & savory', 'Saffron', 'saffron', NULL, FALSE, 'Golden, honeyed, hay-like luxury spice.', '#A8481F', '#F0BFA5', 130),
  ('Roasted', 'Toasted grain', 'Toasted bread', 'toasted-bread', ARRAY['toast']::text[], FALSE, 'Maillard-sweet baked grain.', '#6B4628', '#C9A77E', 10),
  ('Roasted', 'Toasted grain', 'Malt', 'malt', ARRAY['malted', 'barley malt']::text[], FALSE, 'Sweet, roasted, beer-adjacent grain.', '#6B4628', '#C9A77E', 20),
  ('Roasted', 'Toasted grain', 'Cereal', 'cereal', ARRAY['grain']::text[], FALSE, 'Dry, grainy, breakfast-cereal note.', '#6B4628', '#C9A77E', 30),
  ('Roasted', 'Toasted grain', 'Biscotti', 'biscotti', ARRAY['biscuit']::text[], FALSE, 'Dry, sweet, almond-grain biscuit.', '#6B4628', '#C9A77E', 40),
  ('Roasted', 'Toasted grain', 'Graham cracker', 'graham-cracker', NULL, FALSE, 'Honey-grain-cinnamon baked note.', '#6B4628', '#C9A77E', 50),
  ('Roasted', 'Smoky', 'Smoke', 'smoke', ARRAY['smoky']::text[], FALSE, 'Woodsmoke character.', '#6B4628', '#C9A77E', 60),
  ('Roasted', 'Smoky', 'Burnt sugar', 'burnt-sugar', NULL, FALSE, 'Caramel gone dark. Bittersweet-char.', '#6B4628', '#C9A77E', 70),
  ('Roasted', 'Smoky', 'Charred', 'charred', NULL, FALSE, 'Dark-roast char character.', '#6B4628', '#C9A77E', 80),
  ('Roasted', 'Tobacco & leather', 'Pipe tobacco', 'pipe-tobacco', ARRAY['tobacco']::text[], FALSE, 'Sweet, cured, aromatic tobacco.', '#6B4628', '#C9A77E', 90),
  ('Roasted', 'Tobacco & leather', 'Cigar box', 'cigar-box', ARRAY['cedar box']::text[], FALSE, 'Aged tobacco + cedar.', '#6B4628', '#C9A77E', 100),
  ('Roasted', 'Tobacco & leather', 'Leather', 'leather', NULL, FALSE, 'Tanned, savory, aged animal hide.', '#6B4628', '#C9A77E', 110),
  ('Earthy & Wood', 'Earth & mushroom', 'Forest floor', 'forest-floor', NULL, FALSE, 'Damp leaves, moss, humus.', '#2F4A38', '#B5C4A8', 10),
  ('Earthy & Wood', 'Earth & mushroom', 'Damp earth', 'damp-earth', ARRAY['wet soil', 'petrichor']::text[], FALSE, 'Rain on dry earth.', '#2F4A38', '#B5C4A8', 20),
  ('Earthy & Wood', 'Earth & mushroom', 'Humus', 'humus', ARRAY['loam']::text[], FALSE, 'Rich, organic, decomposing-leaf earth.', '#2F4A38', '#B5C4A8', 30),
  ('Earthy & Wood', 'Earth & mushroom', 'Mushroom', 'mushroom', ARRAY['mushrooms', 'porcini']::text[], FALSE, 'Umami, damp, fungal.', '#2F4A38', '#B5C4A8', 40),
  ('Earthy & Wood', 'Wood', 'Cedar', 'cedar', NULL, FALSE, 'Dry, aromatic, resinous wood.', '#2F4A38', '#B5C4A8', 50),
  ('Earthy & Wood', 'Wood', 'Oak', 'oak', NULL, FALSE, 'Structured, tannic, slightly sweet wood.', '#2F4A38', '#B5C4A8', 60),
  ('Earthy & Wood', 'Wood', 'Pine', 'pine', ARRAY['pine resin']::text[], FALSE, 'Resinous, sharp, green wood.', '#2F4A38', '#B5C4A8', 70),
  ('Earthy & Wood', 'Wood', 'Sandalwood', 'sandalwood', NULL, FALSE, 'Warm, creamy, incense-like wood.', '#2F4A38', '#B5C4A8', 80),
  ('Earthy & Wood', 'Wood', 'Sawdust', 'sawdust', NULL, FALSE, 'Dry, raw, freshly-cut wood.', '#2F4A38', '#B5C4A8', 90),
  ('Earthy & Wood', 'Fresh herbs', 'Hay', 'hay', ARRAY['dried grass']::text[], FALSE, 'Sun-dried grass, warm barn note.', '#2F4A38', '#B5C4A8', 100),
  ('Earthy & Wood', 'Fresh herbs', 'Fresh herb', 'fresh-herb', ARRAY['herbaceous', 'herbs']::text[], FALSE, 'Generic green-herb character.', '#2F4A38', '#B5C4A8', 110),
  ('Earthy & Wood', 'Fresh herbs', 'Dill', 'dill', NULL, FALSE, 'Anise-edged fresh herb.', '#2F4A38', '#B5C4A8', 120),
  ('Earthy & Wood', 'Fresh herbs', 'Thyme', 'thyme', NULL, FALSE, 'Piney, peppery fresh herb.', '#2F4A38', '#B5C4A8', 130),
  ('Fermented & Funky', 'Wine-like', 'Red wine', 'red-wine', ARRAY['winey']::text[], FALSE, 'Tannic, dark-fruited, boozy red.', '#8B4E5C', '#D9B8C0', 10),
  ('Fermented & Funky', 'Wine-like', 'White wine', 'white-wine', NULL, FALSE, 'Bright, crisp, floral-boozy.', '#8B4E5C', '#D9B8C0', 20),
  ('Fermented & Funky', 'Wine-like', 'Sparkling wine', 'sparkling-wine', ARRAY['champagne', 'prosecco']::text[], FALSE, 'Yeasty, bright, effervescent-seeming.', '#8B4E5C', '#D9B8C0', 30),
  ('Fermented & Funky', 'Wine-like', 'Port', 'port', ARRAY['tawny port']::text[], FALSE, 'Sweet, dark, fortified wine.', '#8B4E5C', '#D9B8C0', 40),
  ('Fermented & Funky', 'Boozy', 'Rum', 'rum', NULL, FALSE, 'Molasses-distilled, warm booze.', '#8B4E5C', '#D9B8C0', 50),
  ('Fermented & Funky', 'Boozy', 'Whiskey', 'whiskey', ARRAY['whisky', 'bourbon']::text[], FALSE, 'Grain-distilled, oaked, warm.', '#8B4E5C', '#D9B8C0', 60),
  ('Fermented & Funky', 'Boozy', 'Cognac', 'cognac', NULL, FALSE, 'Grape-distilled, refined, aged booze.', '#8B4E5C', '#D9B8C0', 70),
  ('Fermented & Funky', 'Boozy', 'Brandy', 'brandy', NULL, FALSE, 'Grape-distilled, sharper than cognac.', '#8B4E5C', '#D9B8C0', 80),
  ('Fermented & Funky', 'Cultured', 'Apple cider', 'apple-cider', ARRAY['hard cider']::text[], FALSE, 'Tart, fermented apple.', '#8B4E5C', '#D9B8C0', 90),
  ('Fermented & Funky', 'Cultured', 'Kombucha', 'kombucha', ARRAY['tea vinegar']::text[], FALSE, 'Tart, sour, lightly yeasty cultured tea.', '#8B4E5C', '#D9B8C0', 100),
  ('Fermented & Funky', 'Cultured', 'Yeast', 'yeast', ARRAY['bready yeast']::text[], FALSE, 'Bread-dough, slightly boozy yeast.', '#8B4E5C', '#D9B8C0', 110),
  ('Body & Mouthfeel', 'Weight', 'Full-bodied', 'full-bodied', ARRAY['heavy']::text[], FALSE, 'Dense, substantial, fills the mouth.', '#5E4F42', '#C9BBA8', 10),
  ('Body & Mouthfeel', 'Weight', 'Medium-bodied', 'medium-bodied', NULL, FALSE, 'Balanced weight, neither thin nor heavy.', '#5E4F42', '#C9BBA8', 20),
  ('Body & Mouthfeel', 'Weight', 'Light-bodied', 'light-bodied', ARRAY['delicate body']::text[], FALSE, 'Thin, airy, quick finish.', '#5E4F42', '#C9BBA8', 30),
  ('Body & Mouthfeel', 'Weight', 'Tea-like', 'tea-like', NULL, FALSE, 'Wispy, transparent, tea-bodied.', '#5E4F42', '#C9BBA8', 40),
  ('Body & Mouthfeel', 'Weight', 'Watery', 'watery', NULL, FALSE, 'Dilute, under-weighted. Usually negative.', '#5E4F42', '#C9BBA8', 50),
  ('Body & Mouthfeel', 'Texture', 'Silky', 'silky', NULL, FALSE, 'Smooth, liquid-fine texture.', '#5E4F42', '#C9BBA8', 60),
  ('Body & Mouthfeel', 'Texture', 'Velvety', 'velvety', NULL, FALSE, 'Soft, rich, plush texture.', '#5E4F42', '#C9BBA8', 70),
  ('Body & Mouthfeel', 'Texture', 'Creamy', 'creamy', NULL, FALSE, 'Fat-like, dairy-texture mouthfeel.', '#5E4F42', '#C9BBA8', 80),
  ('Body & Mouthfeel', 'Texture', 'Syrupy', 'syrupy', ARRAY['thick']::text[], FALSE, 'Viscous, sugar-sap texture.', '#5E4F42', '#C9BBA8', 90),
  ('Body & Mouthfeel', 'Texture', 'Juicy', 'juicy', NULL, FALSE, 'Saliva-triggering, fresh-fruit texture.', '#5E4F42', '#C9BBA8', 100),
  ('Body & Mouthfeel', 'Texture', 'Round', 'round', ARRAY['smooth']::text[], FALSE, 'Even, unedged, balanced texture.', '#5E4F42', '#C9BBA8', 110),
  ('Body & Mouthfeel', 'Dryness', 'Drying', 'drying', NULL, FALSE, 'Pulls moisture from the mouth.', '#5E4F42', '#C9BBA8', 120),
  ('Body & Mouthfeel', 'Dryness', 'Astringent', 'astringent', NULL, FALSE, 'Puckering, tannic grip on the tongue.', '#5E4F42', '#C9BBA8', 130),
  ('Body & Mouthfeel', 'Dryness', 'Puckering', 'puckering', NULL, FALSE, 'Cheek-pulling tartness or tannin.', '#5E4F42', '#C9BBA8', 140),
  ('Body & Mouthfeel', 'Dryness', 'Mouth-coating', 'mouth-coating', NULL, FALSE, 'Leaves a lingering film.', '#5E4F42', '#C9BBA8', 150),
  ('Defects & Off-flavors', 'Fermentation defects', 'Over-fermented', 'over-fermented', ARRAY['over fermented']::text[], TRUE, 'Uncontrolled ferment. Boozy-rotten.', '#524E48', '#BFB8B0', 10),
  ('Defects & Off-flavors', 'Fermentation defects', 'Phenolic', 'phenolic', ARRAY['band-aid', 'medicinal ferment']::text[], TRUE, 'Chemical, bandage-like fermentation defect.', '#524E48', '#BFB8B0', 20),
  ('Defects & Off-flavors', 'Fermentation defects', 'Vinegary', 'vinegary', ARRAY['acetic', 'harsh acid']::text[], TRUE, 'Sharp, harsh, vinegar-like. Fermentation gone wrong.', '#524E48', '#BFB8B0', 30),
  ('Defects & Off-flavors', 'Storage & moisture defects', 'Musty', 'musty', NULL, TRUE, 'Damp, closed-room staleness.', '#524E48', '#BFB8B0', 40),
  ('Defects & Off-flavors', 'Storage & moisture defects', 'Moldy', 'moldy', ARRAY['mouldy']::text[], TRUE, 'Mold, damp fungal staleness.', '#524E48', '#BFB8B0', 50),
  ('Defects & Off-flavors', 'Storage & moisture defects', 'Baggy', 'baggy', ARRAY['jute', 'burlap']::text[], TRUE, 'Burlap sack, rough-fiber note.', '#524E48', '#BFB8B0', 60),
  ('Defects & Off-flavors', 'Storage & moisture defects', 'Stale', 'stale', NULL, TRUE, 'Past-its-prime, flat, oxidized.', '#524E48', '#BFB8B0', 70),
  ('Defects & Off-flavors', 'Processing defects', 'Potato defect', 'potato-defect', ARRAY['potato', 'raw potato']::text[], TRUE, 'Real defect common in some East African coffees.', '#524E48', '#BFB8B0', 80),
  ('Defects & Off-flavors', 'Processing defects', 'Onion or garlic', 'onion-or-garlic', ARRAY['alliaceous']::text[], TRUE, 'Sulfurous processing defect.', '#524E48', '#BFB8B0', 90),
  ('Defects & Off-flavors', 'Roast defects', 'Burnt', 'burnt', NULL, TRUE, 'Over-roasted. Carbon character.', '#524E48', '#BFB8B0', 100),
  ('Defects & Off-flavors', 'Roast defects', 'Ashy', 'ashy', NULL, TRUE, 'Dry, spent-fire ash.', '#524E48', '#BFB8B0', 110),
  ('Defects & Off-flavors', 'Roast defects', 'Scorched', 'scorched', NULL, TRUE, 'Surface-burned beans.', '#524E48', '#BFB8B0', 120),
  ('Defects & Off-flavors', 'Roast defects', 'Underdeveloped', 'underdeveloped', ARRAY['underdeveloped roast', 'baked']::text[], TRUE, 'Insufficient roast development. Grassy, cereal.', '#524E48', '#BFB8B0', 130),
  ('Defects & Off-flavors', 'Roast defects', 'Baked', 'baked', NULL, TRUE, 'Long, flat roast. Cardboard-sweet.', '#524E48', '#BFB8B0', 140),
  ('Defects & Off-flavors', 'Chemical', 'Rubber', 'rubber', ARRAY['rubbery']::text[], TRUE, 'Tire, rubber-band character.', '#524E48', '#BFB8B0', 150),
  ('Defects & Off-flavors', 'Chemical', 'Medicinal', 'medicinal', ARRAY['iodine']::text[], TRUE, 'Pharmacy, antiseptic note.', '#524E48', '#BFB8B0', 160),
  ('Defects & Off-flavors', 'Chemical', 'Metallic', 'metallic', ARRAY['tinny']::text[], TRUE, 'Iron, coin, metal-like taste.', '#524E48', '#BFB8B0', 170),
  ('Defects & Off-flavors', 'Chemical', 'Soapy', 'soapy', NULL, TRUE, 'Detergent, fatty-soap character.', '#524E48', '#BFB8B0', 180),
  ('Defects & Off-flavors', 'Other', 'Cardboard', 'cardboard', ARRAY['papery', 'paper']::text[], TRUE, 'Flat, fibrous, aged-paper note.', '#524E48', '#BFB8B0', 190),
  ('Defects & Off-flavors', 'Other', 'Rancid', 'rancid', NULL, TRUE, 'Oxidized fats. Spoiled-oil character.', '#524E48', '#BFB8B0', 200);

commit;
